config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root to: "questions#index"

  devise_scope :user do
    post '/register' => 'omniauth_callbacks#register'
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :create, :show], shallow: true do
        resources :answers, only: [:index, :create, :show]
      end
    end
  end

  concern :votable do
    member do
      post :vote_up
      post :vote_down
    end
  end

  concern :commentable do
    resources :comments, only: [:create, :destroy, :update], shallow: true
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true do
      patch :best, on: :member
    end
  end

  resources :attachments, only: [:destroy]

  resources :subscriptions, only: [:create, :destroy]

  get :search, to: 'search#index'

  mount ActionCable.server => '/cable'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  include Attachable
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  belongs_to :user

  validates :title, :body, presence: true

  after_create :subscribe_author

  private

  def subscribe_author
    subscriptions.create(user: user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :set_question, only: [:show]
  authorize_resource

  def index
    @questions = Question.all
    respond_with @questions, each_serializer: QuestionCollectionSerializer
  end

  def create
    respond_with(current_resource_owner.questions.create(question_params))
  end

  def show
    respond_with @question
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: [:show, :index]
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  before_action :build_answer, only: :show
  after_action :publish_question, only: :create

  respond_to :js, only: :update

  authorize_resource

  def index
    respond_with(@questions = Question.all)
  end

  def show
    respond_with(@answers)
  end

  def new
    respond_with(@question = Question.new)
  end

  def edit
  end

  def create
    respond_with(@question = current_user.questions.create(question_params))
  end

  def update
    @question.update(question_params)
    respond_with @question
  end

  def destroy
    respond_with @question.destroy
  end

  private

  def build_answer
    @answer = @question.answers.build
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast 'questions',
      ApplicationController.render(
        partial: 'questions/question_action',
        locals: { question: @question }
      )
  end

  def load_question
    @question = Question.find(params[:id])
    gon.question_id = @question.id
    gon.question_user_id = @question.user_id
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question.html.slim
- cache question do
  p = question.title
  p = question.body

h3 Attachments
= render 'common/attachments', resource: question

.comment_question
  - if can?(:create, Comment)
    = link_to 'Add comment', '', class: 'add-comment-link', data: { resource_id: @question.id, resource_type: "question" }
    = render 'comments/form', resource: @question
  div class="question_#{@question.id}_comments comments"
    b Comments:
    = render @question.comments

- if can?(:action, @question)
  = link_to 'Delete question', question_path, method: :Delete
  = link_to 'Edit question', '', class: 'edit-question-link', data: { question_id: question.id}
  = form_for question, remote: true, html: { id: "edit-question-#{question.id}" } do |f|
    = f.label :title, 'Title'
    = f.text_area :title
    = f.label :body, 'Body'
    = f.text_area :body
    = f.submit 'Save'

app/views/questions/_question_action.html.slim
= link_to question.title, question_path(question)

app/views/questions/index.html.slim
h1 Questions
ul
  .questions_list
    - cache collection_cache_key_for :question do
      - @questions.each do |question|
        li = link_to question.title, question_path(question)
p = link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= form_for @question do |f|
  = render 'common/errors', resource: @question
  p = f.label :title
  p = f.text_field :title
  p = f.label :body
  p = f.text_area :body

  p Attachments:
  p
    = f.fields_for :attachments, @question.attachments.build do |a|
      = render 'common/attachment_fields', f: a
    .links
      = link_to_add_association 'Add file', f, :attachments, partial: 'common/attachment_fields'

  p = f.submit 'Create'

app/views/questions/show.html.slim
h1 Question

-cache @question do
  .question
    = render @question

h3 Votes
p.total_votes data-id=@question.id
  = @question.sum
  = render 'common/vote', resource: @question

.answers
  = render @question.answers.ordered

= form_for [@question, @answer], remote: true do |f|
  = render 'common/errors', resource: @answer
  p = f.label :body, 'Your answer'
  p = f.text_area :body
  p = f.fields_for :attachments, @answer.attachments.build do |a|
      = render 'common/attachment_fields', f: a
  .links
    = link_to_add_association 'Add file', f, :attachments, partial: 'common/attachment_fields'

  p = f.submit 'Answer'

- if can?(:destroy, Subscription)
  .subscription
    .sub
      - if subscription = (current_user.subscribe_for?(@question))
        = render 'subscriptions/unsubscription', subscription: subscription
      - else
        - if can?(:create, Subscription)
          = render 'subscriptions/subscription', question: @question

app/views/questions/update.js.erb
$('#error').remove();
<% if @question.errors.present? %>
  <% @question.errors.full_messages.each do |message| %>
  $('.question').append('<div id="error"><%= j message %></div>');
<% end %>
<% else %>
  $('.question').html('<%= j render @question %>');
<% end %>