config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root to: "questions#index"

  devise_scope :user do
    post '/register' => 'omniauth_callbacks#register'
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :create, :show], shallow: true do
        resources :answers, only: [:index, :create, :show]
      end
    end
  end

  concern :votable do
    member do
      post :vote_up
      post :vote_down
    end
  end

  concern :commentable do
    resources :comments, only: [:create, :destroy, :update], shallow: true
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true do
      patch :best, on: :member
    end
  end

  resources :attachments, only: [:destroy]

  resources :subscriptions, only: [:create, :destroy]

  get :search, to: 'search#index'

  mount ActionCable.server => '/cable'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true, optional: true, touch: true

  validates :body, presence: true

  default_scope { order(updated_at: :asc) }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_commentable, only: :create
  before_action :set_comment, only: [:update, :destroy]
  after_action :publish_comment, only: :create

  respond_to :js
  authorize_resource

  def create
    respond_with(@comment = @commentable.comments.create(comment_params.merge(user: current_user)))
  end

  def destroy
    respond_with(@comment.destroy)
  end

  def update
    @comment.update(comment_params)
    @commentable = @comment.commentable
    respond_with @comment
  end

  private

  def set_commentable
    @commentable = if params[:answer_id]
      Answer.find(params[:answer_id])
    elsif params[:question_id]
      Question.find(params[:question_id])
    end
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end

  def publish_comment
    return if @comment.errors.any?
    question_id = @commentable.is_a?(Question) ? @commentable.id : @commentable.question.id

    ActionCable.server.broadcast(
      "question-#{question_id}:comments",
        { comment: @comment.to_json } )
  end
end

app/views/comments/_comment.html.slim
- if comment.persisted?
  div class="comment_#{comment.id} comment"
    - cache comment do
      = comment.body
    - if can?(:action, comment)
      p = link_to 'Delete comment', comment_path(comment), class: 'delete-comment-link', method: :delete, remote: true, data: { confirm: 'Are you sure?' }
      p = link_to 'Edit comment', '', class: 'edit-comment-link', data: { comment_id: comment.id }
      div id="comment-update-errors-#{comment.id}"
      = form_for comment, remote: true do |f|
        = f.label :body, 'Comment'
        = f.text_area :body
        = f.submit 'Сomment'
        end

app/views/comments/_form.html.slim
= form_for [resource, resource.comments.build], html: { id: "new_comment_#{resource.class.name.underscore}_#{resource.id}" }, remote: true do |f|
  p = f.label :body, 'Comment'
  p = f.text_area :body
  p = f.submit 'Сomment'

app/views/comments/create.js.erb
$('#error').remove();
<% if @comment&.errors.present? %>
  <% @comment.errors.full_messages.each do |message| %>
    $('.comments').append('<div id="error"><%= j message %></div>');
  <% end %>
<% else %>
  $('.<%= @comment.commentable_type.underscore %>_<%= @commentable.id %>_comments').append('<%= j render @comment %>');
  $('#new_comment_<% @comment.commentable_type.underscore %>_<% @commentable.id %>').hide()
<% end %>

app/views/comments/destroy.js.erb
$('.comment_<%= @comment.id%>').remove();

app/views/comments/update.js.erb
$('#error').remove();
<% if @comment&.errors.present? %>
  <% @comment.errors.full_messages.each do |message| %>
    $('.comments').append('<div id="error"><%= j message %></div>');
  <% end %>
<% else %>
  $('.comment_<%= @comment.id %>').html('<%= j render @comment %>').removeClass("comment");
<% end %>