config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root to: "questions#index"

  devise_scope :user do
    post '/register' => 'omniauth_callbacks#register'
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :create, :show], shallow: true do
        resources :answers, only: [:index, :create, :show]
      end
    end
  end

  concern :votable do
    member do
      post :vote_up
      post :vote_down
    end
  end

  concern :commentable do
    resources :comments, only: [:create, :destroy, :update], shallow: true
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true do
      patch :best, on: :member
    end
  end

  resources :attachments, only: [:destroy]

  resources :subscriptions, only: [:create, :destroy]

  get :search, to: 'search#index'

  mount ActionCable.server => '/cable'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Attachable
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user

  validates :body, presence: true

  after_save :notice_subscribers, on: :create

  scope :ordered, -> { order(best: :desc) }

  def best!
    prev_best = question.answers.where(best: true).first
    transaction do
      prev_best&.update!(best: false)
      update!(best: true)
    end
  end

  def notice_subscribers
    NotifySubscribersJob.perform_later(question)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!
  before_action :set_answer, only: [:update, :destroy, :best]
  before_action :load_question, only: :create

  after_action :publish_answer, only: :create

  respond_to :js
  authorize_resource

  def create
    respond_with(@answer = @question.answers.create(answer_params.merge(user_id: current_user.id)))
  end

  def update
    @answer.update(answer_params)
    respond_with @answer
  end

  def best
    respond_with(@answer.best!)
  end

  def destroy
    respond_with(@answer.destroy)
  end

  private

  def publish_answer
    return if @answer.errors.any?
    ActionCable.server.broadcast("question-#{@question.id}",
      answer: @answer,
      total_votes: @answer.sum,
      attachments: @answer.attachments
    )
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:file])
  end

  def set_answer
    @answer = Answer.find(params[:id])
    @question = @answer.question
  end

  def load_question
    @question = Question.find(params[:question_id])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :set_answer, only: [:show]
  before_action :load_question, only: [:index, :create]
  authorize_resource

  def index
    respond_with @question.answers
  end

  def create
    @answer = Answer.create(answer_params.merge(user: current_resource_owner, question: @question))
    respond_with @answer
  end

  def show
    respond_with @answer
  end

  private

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end

  def load_question
    @question = Question.find(params[:question_id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
-if answer.persisted?
  h3 Answers
  div id="answer-#{answer.id}"
    - @question.answers.each do |answer|
    - if answer.best?
      .best-label
        p = 'Best answer'
    - cache answer do
      p = answer.body

    h3 Attachments
    = render 'common/attachments', resource: answer

    h3 Votes
    p.total_votes data-id=answer.id
      = answer.sum
      = render 'common/vote', resource: answer

    - if can?(:best, answer)
      = link_to 'Note as best', best_answer_path(answer), remote: true, method: :patch, class: 'best-answer-link', data: { answer_id: answer.id }
    - if can?(:action, answer)
        = link_to 'Delete answer', answer, remote: true, method: :delete, class: 'delete-answer-link', data: { answer_id: answer.id }
        = link_to 'Edit ', '', class: 'edit-answer-link', data: { answer_id: answer.id }
        = form_for [answer], remote: true, html: { id: "edit-answer-#{answer.id}" } do |f|
          = f.label :body, 'Answer'
          = f.text_area :body
          = f.submit 'Save'
    - if can?(:create, Comment)
      div class='answer_#{answer.id}_comments'
        h3 Comments:
        = link_to 'Add comment', '', class: 'add-comment-link', data: { resource_id: answer.id, resource_type: "answer" }
        = render 'comments/form', resource: answer
        = render answer.comments

app/views/answers/best.js.erb
$('.best-label').remove();

$('#answer-<%= @answer.id %>').prependTo('.answers');
$('#answer-<%= @answer.id %>').prepend('<p class="best-label"> Best answer: </p>');

app/views/answers/create.js.erb
$('#error').remove();
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answers').append('<div id="error"><%= j message %></div>');
  <% end %>
<% else %>
  $('.answers').append('<%= j render @answer %>');
  $('#answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$('#answer-<%= @answer.id %>').remove();

app/views/answers/update.js.erb
$('#error').remove();
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
  $('.answers').append('<div id="error"><%= j message %></div>');
<% end %>
<% else %>
  $('#answer-<%= @answer.id %>').html('<%= j render @answer %>');
<% end %>