config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root to: "questions#index"

  devise_scope :user do
    post '/register' => 'omniauth_callbacks#register'
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :create, :show], shallow: true do
        resources :answers, only: [:index, :create, :show]
      end
    end
  end

  concern :votable do
    member do
      post :vote_up
      post :vote_down
    end
  end

  concern :commentable do
    resources :comments, only: [:create, :destroy, :update], shallow: true
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true do
      patch :best, on: :member
    end
  end

  resources :attachments, only: [:destroy]

  resources :subscriptions, only: [:create, :destroy]

  get :search, to: 'search#index'

  mount ActionCable.server => '/cable'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!

  respond_to :js

  authorize_resource

  def create
    @subscription = current_user.subscriptions.create(question_id: params[:question])
    respond_with(@subscription)
  end

  def destroy
    @subscription = Subscription.find(params[:id])
    respond_with(@subscription.destroy)
  end
end

app/views/subscriptions/_subscription.html.slim
p = link_to 'Subscribe to question', subscriptions_path(:question => question.id), method: :post, remote: true, class: 'subscribe_question'

app/views/subscriptions/_unsubscription.html.slim
p = link_to 'Unsubscribe to question', subscription, method: :delete, remote: true, class: 'subscribe_question'

app/views/subscriptions/create.js.erb
$('#error').remove();
<% if @subscription&.errors.present? %>
  <% @subscription.errors.full_messages.each do |message| %>
    $('.subscription').append('<div id="error"><%= j message %></div>');
  <% end %>
<% else %>
  $('.flash').html("<%= flash[:notice] %>");
  $('.sub').html('<%= j render 'subscriptions/unsubscription', subscription: @subscription %>');
<% end %>

app/views/subscriptions/destroy.js.erb
$('#error').remove();
<% if @subscription&.errors.present? %>
  <% @subscription.errors.full_messages.each do |message| %>
    $('.subscription').append('<div id="error"><%= j message %></div>');
  <% end %>
<% else %>
  $('.flash').html("<%= flash[:notice] %>");
  $('.sub').html('<%= j render 'subscriptions/subscription', question: @subscription.question %>');
<% end %>